#!/usr/bin/env python3
"""
decode_mlc_header.py

Static analyzer for the MLC config arrays generated by json_to_header.py.

Reads an mlc_*.h file and replays the (reg, val) write stream against a
model of LSM6DSOX register banks + paged embedded registers, then prints
a human-readable summary:

  * bank transitions (user / sensor hub / embedded)
  * embedded-paged writes via PAGE_SEL/PAGE_ADDRESS/PAGE_VALUE protocol
  * ODR_PRGS / accelerometer / gyro / MLC enable bits
  * EMB_FUNC_EN_B (0x05): MLC_EN bit
  * MLC0_SRC routing (0x60: which MLC outputs go to which class codes)
  * Filter coefficients written into the MLC paged area
  * Decision tree leaves (heuristic: MLC results table)

Goal: detect three classes of failure independent of the chip:
  (a) json_to_header.py bug -- wrong reg, wrong byte, dropped writes
  (b) MEMS Studio export anomaly -- unexpected bank state, missing INIT
  (c) operator confusion -- wrong file flashed, version mismatch

Usage:
    python3 decode_mlc_header.py mlc_latency.h
    python3 decode_mlc_header.py mlc_accuracy.h

Also can ingest a UCF file directly for cross-check:
    python3 decode_mlc_header.py path/to/file.ucf

This is a diagnostic. It does not flash the chip. It does not require any
hardware. Run it on the laptop or the Jetson, doesn't matter.

References:
  ST AN5259 (LSM6DSOX MLC application note)
  ST UM2575 (LSM6DSOX datasheet)
  ST AN5273 (LSM6DSOX embedded functions)
"""

from __future__ import annotations
import re
import sys
from dataclasses import dataclass, field
from typing import Optional


# ---------- Register name table (only the ones we care about) ----------

USER_BANK_NAMES = {
    0x01: "FUNC_CFG_ACCESS",
    0x0D: "INT1_CTRL",
    0x0E: "INT2_CTRL",
    0x0F: "WHO_AM_I",
    0x10: "CTRL1_XL",       # accel ODR + FS
    0x11: "CTRL2_G",        # gyro ODR + FS
    0x12: "CTRL3_C",
    0x13: "CTRL4_C",
    0x14: "CTRL5_C",
    0x15: "CTRL6_C",
    0x17: "CTRL8_XL",
    0x18: "CTRL9_XL",
    0x19: "CTRL10_C",
    0x5E: "MD1_CFG",
    0x5F: "MD2_CFG",
}

EMB_BANK_NAMES = {
    0x02: "PAGE_SEL",
    0x04: "EMB_FUNC_EN_A",
    0x05: "EMB_FUNC_EN_B",
    0x08: "PAGE_ADDRESS",
    0x09: "PAGE_VALUE",
    0x0A: "EMB_FUNC_INT1",
    0x0E: "EMB_FUNC_INT2",
    0x14: "FSM_INT1_A",
    0x17: "PAGE_RW",
    0x60: "MLC0_SRC",   # the class-output register the chip serves to MLC0_SRC@0x70 user-side mirror
    0x70: "MLC0_SRC",   # actual readable output (in embedded bank)
}

ODR_XL_MAP = {
    0x0: "power-down",
    0x1: "12.5 Hz",
    0x2: "26 Hz",
    0x3: "52 Hz",
    0x4: "104 Hz",
    0x5: "208 Hz",
    0x6: "416 Hz",
    0x7: "833 Hz",
    0x8: "1.66 kHz",
    0x9: "3.33 kHz",
    0xA: "6.66 kHz",
    0xB: "1.6 Hz (low-power)",
}
FS_XL_MAP = {0x0: "+/-2g", 0x1: "+/-16g", 0x2: "+/-4g", 0x3: "+/-8g"}


# ---------- Parsers ----------

C_PAIR_RE = re.compile(r"\{\s*0x([0-9A-Fa-f]{2})\s*,\s*0x([0-9A-Fa-f]{2})\s*\}")

def parse_c_header(text: str) -> list[tuple[int, int]]:
    pairs = []
    for m in C_PAIR_RE.finditer(text):
        pairs.append((int(m.group(1), 16), int(m.group(2), 16)))
    return pairs

UCF_LINE_RE = re.compile(r"Ac\s+([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})")

def parse_ucf(text: str) -> list[tuple[int, int]]:
    pairs = []
    for m in UCF_LINE_RE.finditer(text):
        pairs.append((int(m.group(1), 16), int(m.group(2), 16)))
    return pairs


# ---------- State machine ----------

@dataclass
class ChipModel:
    bank: str = "user"          # user | sensor_hub | embedded
    page_sel: int = 0           # PAGE_SEL value (which page of paged regs)
    page_addr: int = 0          # PAGE_ADDRESS auto-increments after each PAGE_VALUE write
    page_rw: int = 0
    paged_writes: dict[int, dict[int, int]] = field(default_factory=dict)
    user_regs: dict[int, int] = field(default_factory=dict)
    emb_regs: dict[int, int] = field(default_factory=dict)
    bank_transitions: list[str] = field(default_factory=list)
    anomalies: list[str] = field(default_factory=list)
    write_count: int = 0


def replay(pairs: list[tuple[int, int]]) -> ChipModel:
    chip = ChipModel()

    def bank_set(new):
        if new != chip.bank:
            chip.bank_transitions.append(f"#{chip.write_count}: {chip.bank} -> {new}")
            chip.bank = new

    for i, (reg, val) in enumerate(pairs):
        chip.write_count = i

        if chip.bank == "user":
            if reg == 0x01:  # FUNC_CFG_ACCESS
                top2 = (val >> 6) & 0b11
                if top2 == 0b00:   bank_set("user")
                elif top2 == 0b01: bank_set("sensor_hub")
                elif top2 == 0b10: bank_set("embedded")
                else:
                    chip.anomalies.append(
                        f"#{i}: FUNC_CFG_ACCESS={val:#04x} has reserved bits {top2:#04b}"
                    )
            else:
                chip.user_regs[reg] = val

        elif chip.bank == "embedded":
            if reg == 0x01:  # FUNC_CFG_ACCESS still works in embedded bank to leave
                top2 = (val >> 6) & 0b11
                if top2 == 0b00:   bank_set("user")
                elif top2 == 0b01: bank_set("sensor_hub")
                elif top2 == 0b10: bank_set("embedded")
                else:
                    chip.anomalies.append(
                        f"#{i}: FUNC_CFG_ACCESS={val:#04x} has reserved bits"
                    )
            elif reg == 0x02:  # PAGE_SEL: which page (4 bits) + RW enable (bit 6)
                chip.page_sel = (val >> 4) & 0xF
                chip.emb_regs[reg] = val
            elif reg == 0x08:  # PAGE_ADDRESS
                chip.page_addr = val
                chip.emb_regs[reg] = val
            elif reg == 0x09:  # PAGE_VALUE -> writes one byte at (page_sel, page_addr++)
                page = chip.page_sel
                chip.paged_writes.setdefault(page, {})[chip.page_addr] = val
                chip.page_addr = (chip.page_addr + 1) & 0xFF
            elif reg == 0x17:  # PAGE_RW
                chip.page_rw = val
                chip.emb_regs[reg] = val
            else:
                chip.emb_regs[reg] = val

        else:  # sensor_hub
            if reg == 0x01:
                top2 = (val >> 6) & 0b11
                if top2 == 0b00:   bank_set("user")
                elif top2 == 0b01: bank_set("sensor_hub")
                elif top2 == 0b10: bank_set("embedded")
            chip.anomalies.append(
                f"#{i}: write to sensor_hub bank reg {reg:#04x}=0x{val:02X} -- "
                f"unexpected for an MLC config"
            )

    if chip.bank != "user":
        chip.anomalies.append(
            f"END: chip left in {chip.bank} bank, not user. Subsequent user-bank "
            "reads will fail. The .ucf is supposed to leave the chip in user bank."
        )

    return chip


# ---------- Reporting ----------

def summarize(chip: ChipModel, source_label: str) -> None:
    print(f"=== {source_label} ===")
    print(f"Total writes: {chip.write_count + 1}")
    print(f"Bank transitions: {len(chip.bank_transitions)}")
    for t in chip.bank_transitions:
        print(f"  {t}")
    print()

    # User bank highlights
    print("--- User-bank registers (final state) ---")
    for reg in sorted(chip.user_regs):
        name = USER_BANK_NAMES.get(reg, "?")
        val = chip.user_regs[reg]
        line = f"  {reg:#04x} {name:<18s} = 0x{val:02X}"
        if reg == 0x10:  # CTRL1_XL
            odr = (val >> 4) & 0xF
            fs  = (val >> 2) & 0x3
            line += f"   [accel ODR={ODR_XL_MAP.get(odr,'?')}, FS={FS_XL_MAP.get(fs,'?')}]"
        elif reg == 0x11:  # CTRL2_G
            odr = (val >> 4) & 0xF
            line += f"   [gyro  ODR={ODR_XL_MAP.get(odr,'?')}]"
        elif reg == 0x0D:  # INT1_CTRL
            line += f"   [INT1 routing byte; nonzero = something routed to INT1]"
        print(line)
    print()

    # Embedded bank highlights
    print("--- Embedded-bank direct registers (final state) ---")
    for reg in sorted(chip.emb_regs):
        name = EMB_BANK_NAMES.get(reg, "?")
        val = chip.emb_regs[reg]
        line = f"  {reg:#04x} {name:<18s} = 0x{val:02X}"
        if reg == 0x05:  # EMB_FUNC_EN_B
            mlc_en = bool(val & 0x10)
            line += f"   [MLC_EN={'1 (enabled)' if mlc_en else '0 (DISABLED!)'}]"
        elif reg == 0x04:  # EMB_FUNC_EN_A
            line += f"   [pedo/tilt/sigmot bits]"
        elif reg == 0x0A:  # EMB_FUNC_INT1
            line += f"   [embedded -> INT1 routing]"
        elif reg == 0x60:  # MLC source class register
            line += f"   [MLC0..3 class codes lo/hi nibble pairs]"
        print(line)
    print()

    # Critical health checks
    print("--- HEALTH CHECKS ---")
    health_ok = True

    # 1. MLC enable bit must be set
    enb = chip.emb_regs.get(0x05, 0)
    if not (enb & 0x10):
        print("  [FAIL] EMB_FUNC_EN_B bit MLC_EN (0x10) is not set. The MLC will "
              "not run on this config.")
        health_ok = False
    else:
        print("  [ OK ] MLC_EN bit set in EMB_FUNC_EN_B.")

    # 2. INT1_CTRL or EMB_FUNC_INT1 should route MLC to INT1 if you want INT
    int1 = chip.user_regs.get(0x0D, 0)
    emb_int1 = chip.emb_regs.get(0x0A, 0)
    md1 = chip.user_regs.get(0x5E, 0)
    if emb_int1 == 0 and (md1 & 0x02) == 0:
        print("  [WARN] No embedded routing to INT1 visible (EMB_FUNC_INT1=0 AND "
              "MD1_CFG bit1=0). MLC will run but won't fire INT1. Polling will "
              "still work.")
    else:
        print(f"  [ OK ] Embedded routing to INT1 present (EMB_FUNC_INT1=0x{emb_int1:02X}, "
              f"MD1_CFG=0x{md1:02X}).")

    # 3. Accelerometer running?
    ctrl1_xl = chip.user_regs.get(0x10, 0)
    odr = (ctrl1_xl >> 4) & 0xF
    if odr == 0:
        print("  [FAIL] CTRL1_XL ODR is power-down. Accel won't produce samples; "
              "MLC has no input.")
        health_ok = False
    else:
        print(f"  [ OK ] Accel ODR = {ODR_XL_MAP.get(odr,'?')}.")

    # 4. End-state bank
    if chip.bank != "user":
        print(f"  [FAIL] Chip left in {chip.bank} bank. User-bank operations afterward "
              "will read wrong registers.")
        health_ok = False
    else:
        print("  [ OK ] Chip left in user bank.")

    # 5. Paged writes count
    paged_total = sum(len(v) for v in chip.paged_writes.values())
    if paged_total == 0:
        print("  [FAIL] Zero paged writes. No filter coefficients, no decision tree, "
              "no MLC config. This is an empty .ucf.")
        health_ok = False
    else:
        per_page = ", ".join(f"page{p}={len(v)}" for p,v in sorted(chip.paged_writes.items()))
        print(f"  [ OK ] Paged writes: {paged_total} total ({per_page}).")
    print()

    # Anomalies
    if chip.anomalies:
        print("--- ANOMALIES ---")
        for a in chip.anomalies:
            print(f"  {a}")
        print()

    print(f"OVERALL: {'PASS' if health_ok else 'FAIL'}\n")


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    for path in sys.argv[1:]:
        with open(path, "r") as f:
            text = f.read()
        if path.endswith(".ucf") or "Ac " in text[:200]:
            pairs = parse_ucf(text)
        else:
            pairs = parse_c_header(text)
        if not pairs:
            print(f"{path}: no (reg, val) pairs parsed -- check format", file=sys.stderr)
            sys.exit(2)
        chip = replay(pairs)
        summarize(chip, source_label=path)


if __name__ == "__main__":
    main()
